/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "core.users.index": [],
    "core.users.show": [
        {
            "name": "user",
            "required": true,
            "binding": "uuid"
        }
    ],
    "team.members.index": [],
    "team.members.show": [
        {
            "name": "member",
            "required": true
        }
    ],
    "team.members.store": [],
    "team.members.update": [
        {
            "name": "member",
            "required": true,
            "binding": "id"
        }
    ],
    "imprint": [],
    "privacy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
